language: python
git:
  depth: 3
branches:
  only:
  - master
python:
- '3.7'
install:
- pip install -r requirements.txt
script:
- export
- python3 DeleteMyHistory.py
env:
  matrix:
  - UUU=kkk
  global:
  - secure: CcqrtQgaCVU22uLVWdD+OltMOeTkYebGIpJruShcfN+7geZloYaycXTfSI0Zu37FTeKxxrgQzBf1hGKOXzM/Wu7PwoDaFFwYydTThzFEhZSQroOLx+QuX5LnP0zKL/NidGuyiOAXQiL9YW5Hp8nYLrjqHzDCeIC3GyQb9Vk6xveVDkoFWQ8pzM/4H52cT1+RVogu7IOPjsvFYaC2ZWtlZ3jt6dphWRph6hvqWG7BpVG34ZrmBRrl86NiYGxjopWbiwFL+uoMnxsxZqnzY1w3gQALJavo4KjpiPJ3BvoRz24CJYscidoTlre5+rYG7erGJl5tm2+lFPOJksYczKxTFeEb7hkVuiNtkhb0kM7YVji42onZ8/oFJmPvtR7TmAQvVt9jVEGEUY+GNFNji097ZqgYwHEEUm3q31vwvBau65AAO2qv2wcNjQGMsTUAzitizV1B3soQI375vO+TQd9agUYDqXj1Tc4f2FBwfhABUcwCqaXKc0m2WoLMMhQ0v5PsBYgiWo6PqggiDAXrugmIsYTjd4cMUJDfG4Hem7KRXF9bX4ENfnHMy6VuaMO1iuv2RjvtGPhygrg+hM90C2wleI8YKblcUbWjynQ3/9kS+0MKoLH6grRj/ljLnN/sgu2UZqDd1Vw9P2F7YJ4hEIi5lZaMUzHv7osFexQbZGFLRK8=
  - secure: Hatih2wTCrdL4jHBhpENJlKeeuoVAFCIgnADWlO24sueSCrYjgN0FVP0Xf4bAm931aT95qrJiHMH+OQg1B+gau8ua4kR6y4Mr4+iPsAJCITTjjEhLpbmltC4F2hygnrByxDCTZTzo0zdyBeMiumwhB62AMcrEWpXqNnnrv3qagVOYf/tNr9ijApCGUQADrMkYl5wrK8HeWdtHUhf9yXt49W83bgJqz8Atn0jOwOspsaoddAouv6gCn1tfX9RCQ2agBcGSe+MdioiLUpm7WceFtI1K3lZxy6/NVBcbHLy7VXOQdE3QZ4E4E36nlHj2edVGgGAh9mFFnWuznPkFnQPGYI1jaGbv2+JW3eg2qZQAH6neGq5E8rYiDVSTpUI0CIvjs5KI9UMQAHEriTtEAZsbVpCOfjZn+MjSGDZlesBWMjr3kM2gZSKbhvImRrYqtCKMjuo3lNoRH3HUxRHkQrLhwNqKullHgpXOjwN3eaeMjL2vhoSdMNeNNQD2Jydk6mqh4gA+Xcfv3UT9Npv/G4gmu1CDQ6NEAD+EbnPMw1Pzm9JtcR612A2sFn74Md1ZroqZ3vTQGooTu1R9Ow133875Je67zsBKvIPAmP0N7GNHSpMHwGfqkN4nbQ9vgovhWN2d9G1Hc9IIau7eib/0MtKYkGFWC/D+KTQ3BQ3seXwaD8=
