language: python
git:
  depth: 3
branches:
  only:
  - master
python:
- '3.7'
install:
- pip install -r requirements.txt
script:
- export
- python3 DeleteMyHistory.py
env:
    - secure: WlilCIO00n4ojnV81MZYGOFplpNi1cXrA1FdGrTJ2gxUHljkIMs2Fx00CUFjZPE0s/s6RK5/nZtaZ8kLqUT8deVM9p0J8WFDRPrSGYsnC+cL1mSkek8M8Zcp0P0qpd6KSWfm2KJwV/XX7eIKsiYFSQsdQiw87EXVd+Kbfw6t82PgTH4Nty5XhnYtQ/4qdegxlfo0GnU6yw6tQrfWP1b+z7EzRi8Q/2XXS4KtwUO4r8GqGZylBkVqIJJp04Wqu9vSduXd93LYLQYC0GLCzhrF++UTKjdd9h5/bE6g505SVHkDSDACJ+/J5I5Nga8DV2sPMzETjhuKRwSDTH5BLnM9/TbZJFVKALcz0MJI6dIZMyXah3qP4LHZ0xiiTNXwwPVF7xUSt0RnpRM4Dn9SZ6/QD5wJPN6+fR17prBJL4v4SaNtaOOoaT//g4C6O+yATB/PXv6U+T5wf9XaR7Up1HwT6T++AVC7bcj1LhwiZUkcUDfW+1lUjR67jWpzsL7l80zEMzwzHXzxagHA4c88O1LobgCYQgRN6Ao628Jw08KazykwP9w6IEfhtj1+EtMqwijXWZyIYBdwkORGft1uQ9guvu+/VLGDQlTxubRQSfXqyv2aTk9DSgFaedA7bv4439uSPCXBDKOnev34xKQiIfC43RIk37whZmfSOs+G0COeYmU=
