language: python
git:
  depth: 3
branches:
  only:
  - master
python:
- '3.7'
install:
- pip install -r requirements.txt
script:
- export
- python3 DeleteMyHistory.py
env:
  matrix:
  - UUU=kkk
  global:
  - MMP=111
  - secure: CcqrtQgaCVU22uLVWdD+OltMOeTkYebGIpJruShcfN+7geZloYaycXTfSI0Zu37FTeKxxrgQzBf1hGKOXzM/Wu7PwoDaFFwYydTThzFEhZSQroOLx+QuX5LnP0zKL/NidGuyiOAXQiL9YW5Hp8nYLrjqHzDCeIC3GyQb9Vk6xveVDkoFWQ8pzM/4H52cT1+RVogu7IOPjsvFYaC2ZWtlZ3jt6dphWRph6hvqWG7BpVG34ZrmBRrl86NiYGxjopWbiwFL+uoMnxsxZqnzY1w3gQALJavo4KjpiPJ3BvoRz24CJYscidoTlre5+rYG7erGJl5tm2+lFPOJksYczKxTFeEb7hkVuiNtkhb0kM7YVji42onZ8/oFJmPvtR7TmAQvVt9jVEGEUY+GNFNji097ZqgYwHEEUm3q31vwvBau65AAO2qv2wcNjQGMsTUAzitizV1B3soQI375vO+TQd9agUYDqXj1Tc4f2FBwfhABUcwCqaXKc0m2WoLMMhQ0v5PsBYgiWo6PqggiDAXrugmIsYTjd4cMUJDfG4Hem7KRXF9bX4ENfnHMy6VuaMO1iuv2RjvtGPhygrg+hM90C2wleI8YKblcUbWjynQ3/9kS+0MKoLH6grRj/ljLnN/sgu2UZqDd1Vw9P2F7YJ4hEIi5lZaMUzHv7osFexQbZGFLRK8=
  - secure: lptb9Kq6jNuBi4mWX8CujXt5Enb+0Lk4w79Z8+wCjE8ovhm9DPpwBjVN/S3J2kPnR6LtN9jgSy93Ac82KaE2N3IApYgj0uRozfpTgJOKOL9GMmP62ARZ3JWM74f1iSBMqbcjoxb6rjjjUU0itpvGlh3IENtvyvgxd/SGsGL3s2PTnytqMBxy+5JuXDyvMX8yAfi8z8rf78HSrZePhpIEoiSF+otMYone3rzSABjKEs4NFrD577CxEv8UwAdjvm32eP0nDNOeQF6ktfWU2fblhxjSdBCyH5Doqz6jIsjD8npWOB8bR3QoVMsnyP3C50asLs0UOUm0DI8RD0SyQlbzWLDRVSDkQSoijwTBTMftEBr8KRfbVHHxGTNxIkSIYyVgiG/iYfrrmKEBtrjR2sTzXYSYfDcC8ZskIHoKRgn0PZpi41DVlLn4d3eYWNI92ILiRY9sOUw07BQs7IMt87w8PoEJa3y4I5nXQrG0a3lGXM3I80pqfRa8VVi/zeYhY2b0WNBfXdQKiTaHXVunQXLg/lY8WeR9MlHBwY5A68uHepw7xgJ3yfP3b+OLCsLxJED5xvt2q0WBpVACwm0lhuN2JrOizsJ9fNZhAGOPj7TAE0YbDS3aPhcbthu+mnIY1f+LIpqU78JnknrltU4CBb2k5vKs88T/prwjlR5vka4cKpM=
