language: python
git:
  depth: 3
branches:
  only:
  - master
python:
- '3.7'
install:
- pip install -r requirements.txt
script:
- export
- python3 DeleteMyHistory.py
env:
  matrix:
  - UUU=kkk
  - secure: RKUDK2Clw9mAZGddmnlc03cYaiXNehhkkDLmrGwmUsQSNfM6RWYEglI9+yxcCJu2gidvQXZbA2vw7cXUgV3u5I/JOhtoV8Wr4s7X+KWSO7EI3HYGXbJm5BiyxXIOY7gJlusUq5AY7OZC8guzew72IvmXtPrKJOKX73YwDlg1z8FFqN6NQh8JnhMXccD/Q4wUorcL74/mN63Gnf+pn2zn8U79OQNfU1A4T8vhpdodXQUi8acwyIuCe3tj21OkmDCu5lg8oiZhfrMrVqAaUGdxpyLDqoJckSnklWw2OydliSrtLIOf40W140syV0ug95xWd30JXIYhDFs7/tTC3pVrQwKQEFAxT6HRUeq9KrXWQTmibm9sOAMXDHmY3m/mvSQunLASZ7W/8Rq+MIlw3Fvtzf+SSNmATzNOOzvsbtYlOxSLHooJUhN2mOLojnmqNTq8GjUAye24zOebZm9ZB2GcLvnpjntFLfX4V39sUtBZuBk3PM6nYdKDmBLJULbIEj+LufViAB1Yh/mR4umLifav+QpAvta49eghM5+RYWD050BWxZ2w0iUK5iQjQZ6XFRb2bSZ79kGTN9NTF6qSDu0hNpDp5Kcimi1l1j0JTcE/VqgX14sUfo63Ogfz/EgjNrVxaRbOchfxijM+AKzMDoaE29J4TfkHV97/HebCCEuqHLk=
  - secure: ij0urfdnYSpzmqW1oyf8KfWrLB7tzXhC1Fb7HXyb61rpPnZj6Ggpg5IpCpX/OOpPAI117N8w60q4RcfrHDzLOabzLmG72uPkyT/eFefJ4RFjKDiGP6bAU7lzLCalMe3hM6uJ164QDxEHmrazg8MFFaXXdeQhRCOHPPOwiwR4oR6PBAOeqhgXYNDDP+mPZOsjGhZ/kNWRYu4D9kfqDf1+Tb5HYElugTztPJrrcEuUiCYyQnbqUa4oeX1BmGLAcFjCcKJX0vma5qWfK4q/JxH2RY6xDMF9l3PC4OKbLW+nxZJN6D1QGbuX2mE/Pi6u8fsEyc1F3oABggqw4jgRnhUy1oG+aeVxKTjtNHGBB0QQfgw5JnX0B3E2E+bTJlcnRfnhz/wlJ4QTc/L3Yq/h5lI0EXJN87RoOirotM/wElcAXZG3WhIfq65zOeBu/Cw5/16mEaDw5SLNMMssVUW86getu0BZxVbLwnZLdYZrduHJ1wYeOTFYBJS0n2zc2EgDy/X7RfmhPaIIhSX8HSVg5EElUbKaPXBy5wFm5jKF6ea2hpf7ixj4TcGkzzCqzUU8s2n7OPp8FlhbRmM/HyhthgeMQBR86kf4P4zRx0tHm/VNkhmaCNXN3+XtaZuSUij3md32O77rtHYSX6pH2czIYosFGgyK4nqRzEfBRG/YTZfKsPQ=
  global:
    secure: q0oqTo8Vsz4G8UA2fpLolR+pRzxfFL3rDc6Q/OT5O++3tpcSAeoFDjM72ILRuzgxOBpSujXjw8q0i/jquZjqG7FEo0gmYZNFYJGDuPMd0rYg4eiBG/xqaBBMtCK7ryDGHsIaraElK2ao8ZX4W9u+W29u47Xyjd/qxP1a75ZsheEu98q9xoY0kQD9atnq6coFEJE0cx9xcLV9B6w4cM1T0rD45U0P/znkvgnUsAM97MWVk4FuzCUa+HvoVOBpt8NYYnwFAB+Z6sBaatqihapnDd0RWps0TIY8RqjdIY/jck6scyoY7HDHddvB+MePM1kKiqfb4oY+9etgr9XmqPdeI4x/Bp7DrQem9UsRG9Ncdu2uGXVGJrzFSVXdPwcWU2nvw6gHWMj1Hvh7+mH27H/dGPHd10Ef3YTpQ4AbZf9JP3PHUHrnSYETlUWTJQ3k9m9REoD6AsDf5VruNc3jUBQBLksgt3ZEJv+vZ4yqn4Hv3FQCXRU9c0brfRw9mwcgV7SDBMBKyfJncNWcgJ9p1qDglN72h6OUAe50pS96zgssZgwN0ptrP76ngtzbPl9Jf9AjjwhW/BqahRVoMF0Mh3tbJxwk2nrsyxxGwMZqhHazXTPbFMi3zberkY0E66lco41hwl3esLADyLXGSvvUXtG+Chv6QoVuX3ImJy3rmGew234=
