language: python
git:
  depth: 3
branches:
  only:
  - master
python:
- '3.7'
install:
- pip install -r requirements.txt
script:
- export
- python3 DeleteMyHistory.py
env:
  global:
  - secure: a4ceDxrnwuAhnp2dNHY67H1nYhXRhXdSB276toqJ+mF9bQzYu4RVV5pDk7fWjL9Y0wEu49nh91RNXpekeL1v2oy0EpQk+CaKDesZNR8IfbSVbGPzzkhix8tVIydiobpN6LZqSQCQd7/remC7bjAPiGM55TY0X9kdOkpDr8JO6jvqhXFc2yYcZU5MJ8Gw1on3ZePfh76K50wqxKpM4y2TGUfISdK2jsDXg2dHQHNOhyl99skMZXZC9bJFERDZRcLYWLuaAj8pKA/vg5yWmPOGuBFVcxiILz8TxkDeYCnvxtznkf59TesCGYjGzI9oxND+/ofmpbIVKKj+4YXx9xUe3KrdDWsWA3ydXDpLf7OEr6NO1aexiybo/950pGZaxJkvwKW6+KCt8RRlqnpKjTdxII8Ybf2YiXUsjYa0jEY2nMqGxmFG0jEDNf+LxowqGTTxfXRPiSYWomh5jobiydZxyq9UazUc04AI4aSNjTEq1M1dlK/N9fIs/pSBPCms3NFyhoDT7O1VRjcdW1kUmtEE9ai/fPvnlBJYpxPv534UCCcKXpUvcG0dpGYCzR6wmEysqUz0dpOaChVsRMCAKe6vcCUhpT/nl+TtctBHDVBZenIZ0v9QC/NrY1hu55CTChGbyTXdzoLSnxldsqyeDhU9UTkL/UIHeGg5W7wjCS+NxUU=
  - secure: VdxIpCElpaY+ixkoSyYheIjx8NlSn1Uui74zTInLV1cF/yCEhYGFaWHTQ+NqQcdfDRvEXSMhru/MDpPNW5eR0TipUT1XaPB7Kx/jA2b+ObX2g/q/hW0QIHyir4Vr0h3f3WXXYu0i/TR718EOik9EEAQCuKgsXRKwAetAEuUR3pTofVejnCNJ613xvNAfWTP6P6lnH4NaTC9BPfa9xpbfpzyxWR6UuaFrhPAx5qFxZcApfmEHddsipmD9M4jZ4Zym20271+8bcJzetevzGYenV1iuyu5eb/o/hguJOW1+x23Ys228s4v+0I6+HWkAOykglL0v5JVvi182afmYaym/jWJTGuA6LUL9zVSQBie2a+5wc0q5Vvk/4NVR6nnIkmjsYDDpNe8XufvMNxojrNliEbsLAHiDAAPsA1Sn2AyBBbochcN2Z7wv1r2fOecjOzjweQo6smRgt/T8XH9HZ41EL4ZOW3FxRWxz3JKeD9VNrf7XRnvmPG9SD90nN7IGw3en30W3HGL4EoDF5RgIxnYhmdiW8E8uI+7GTnSmdVqAIBBnXzDdHJDVZFFZxC2iDJenSwpS/gIiwyXGMzDDlGlg8zc06QyBbu4dbBJGPhpLNL3ekyCVWzJayau7O88avFbJ/I+pKW7Prig12fV/TkK/ohUxT6X918b80ATtYaSRW8I=
  matrix:
  - UUU=kkk
