language: python
git:
  depth: 3
branches:
  only:
  - master
python:
- '3.7'
install:
- pip install -r requirements.txt
script:
- export
- python3 DeleteMyHistory.py
env:
  matrix:
  - UUU=kkk
  global:
    secure: oNrebOpteZ+jtVIc8DVTJvtlaLUdcq7CBlTaFdJEhuCA7Et29N2WiDN299twhsobP181Xn0632hIt1FvggQPMdMMwJDWvEJOMAoy9GKFU2hGfEV8hFmWEVVs0L6a4YcfqyAEr/LlYev3wLqDVAdcWfv3gqGLCXV1h+YNDt91woIbn/RMeBNnyAWi0ilNl5XflbOO23XTQkbJP9VpyjPuVaAw4L/WE9juLDN6/yNhO5nYGgniA+dsnViOtnXuD7a4GnNA6Q5v1pofKHMfIr36tvcZ6Ms4o1Z7Hdv6ZHw5giLd9jPwAL+uI4XO0OvLnlojEdhxulObTTeiSAHiBam6DfBspDQDce+Ue3IuwLE3sFOfApUCRCFxAHlS+vSu8ZuVkoYM1D70r3+866Pa6+MH74EM3s4ZY2oIl9VFEf09A5tDX3GHUiPzCiDOYRisZJSE/bRscRjFZRQLn3P8qIMNXs6wu0nCiW41C9uYobz8C9sLd2iM0tSXDR5yMfskIvqIh6QIz4Xz6wKMlbwfsidmqiF0kvDlKcZlHgLapf7SQPVgp7TXcrBqHx3mT2Cvu7wQhdYW/aPsuSMkQecZgRPLWIZ7xHMYBGFGERHiNOELU/ULOwBO8RapxsOOnoSFE55POqSN4EvTJ02UPT4pyShLouAFVzEEbuhtqJHiM4mdL40=
