language: python
git:
  depth: 3
branches:
  only:
  - master
python:
- '3.7'
install:
- pip install -r requirements.txt
script:
- export
- python3 DeleteMyHistory.py
env:
  global:
  - secure: dXdu0SAMlaQBeyBLJVI+SP5QuTo6X9krpKLiiUZ86ShsChV42Xm8j+RdR9fhhbdhXyjxKAr4e3UafobY4QXg3wqUFu1DVuPXwY+jKkrqpkGSi4BsxLUdFOlSIMNJAhMYj7/cXkyPm1boOu4cLVXZMeWvZ2PmpmnxZW94jn3DbRwppAgQ5Tnog9tgWhvL7D273Ut8K7NGAemirM3w0PT8H6QLOLfQRxJQJrEu6BI34BhtkBPeZVr99NklNZSrjTeC+HSmOKwxpmPWFEitywoNUq2g0U0mpJXGD994aw0w/pCceCLUJlQwe9hB6MRG1u3qAfHj82ZvjvlT+FHjXX0kRnmKICRF/9CltJYXWGydCSN+YRyyaJc5y8aFdKovet89NKDprAAgR6DxPKrn3MsSXol6PgYSFLVrY06aPKprUAPtM5Ir7yoBEkPFtknyXMsQKjGM1CfYy4T/ulAHBbOtwW0ktzQPYE6gu6tSV8kJkSUU4GF1CbbEajLNR+OS5hAwhaD+BJnkgrBv07QEaMF3f16UHIQw7h5P31FmFT70Xw/wrAAIfoqlGnuosYp/ObtPdNGqHj1lsE5cAJzteBPFMyxxbTc1lW8+8iGM6hwqIE8y6fIX7WFdRiSRC2uWdoYIlQ4Eoq356AbppRxEH2Xu9xcz9rM/8HvnTstiNsr4Zg8=
  matrix:
  - UUU=kkk
