language: python
git:
  depth: 3
branches:
  only:
  - master
python:
- '3.7'
install:
- pip install -r requirements.txt
script:
- export
- python3 DeleteMyHistory.py
env:
  matrix:
  - UUU=kkk
  global:
    secure: q0oqTo8Vsz4G8UA2fpLolR+pRzxfFL3rDc6Q/OT5O++3tpcSAeoFDjM72ILRuzgxOBpSujXjw8q0i/jquZjqG7FEo0gmYZNFYJGDuPMd0rYg4eiBG/xqaBBMtCK7ryDGHsIaraElK2ao8ZX4W9u+W29u47Xyjd/qxP1a75ZsheEu98q9xoY0kQD9atnq6coFEJE0cx9xcLV9B6w4cM1T0rD45U0P/znkvgnUsAM97MWVk4FuzCUa+HvoVOBpt8NYYnwFAB+Z6sBaatqihapnDd0RWps0TIY8RqjdIY/jck6scyoY7HDHddvB+MePM1kKiqfb4oY+9etgr9XmqPdeI4x/Bp7DrQem9UsRG9Ncdu2uGXVGJrzFSVXdPwcWU2nvw6gHWMj1Hvh7+mH27H/dGPHd10Ef3YTpQ4AbZf9JP3PHUHrnSYETlUWTJQ3k9m9REoD6AsDf5VruNc3jUBQBLksgt3ZEJv+vZ4yqn4Hv3FQCXRU9c0brfRw9mwcgV7SDBMBKyfJncNWcgJ9p1qDglN72h6OUAe50pS96zgssZgwN0ptrP76ngtzbPl9Jf9AjjwhW/BqahRVoMF0Mh3tbJxwk2nrsyxxGwMZqhHazXTPbFMi3zberkY0E66lco41hwl3esLADyLXGSvvUXtG+Chv6QoVuX3ImJy3rmGew234=
