language: python
git:
  depth: 3
branches:
  only:
  - master
python:
- '3.7'
install:
- pip install -r requirements.txt
script:
- export
- python3 DeleteMyHistory.py
env:
  matrix:
  - UUU=kkk
  global:
    secure: PVvU8VhATVx8Z4lRsudx6BbAVLp3jLoZ6O1EF4kAn/UpIq2I2Zh86Lu1l8lrj3eYw5c3DzRqmayFBw0clKDIB+2401hjc8LL4mWexdwOeE7DkiNAQO6fRqTrfRKwzfeXsdaydVNQYeTr2OEzNmfsa2lZJIXUnSs/vGKdqAYu9UQ7krazomIfjIIlQy7Ec/J66bzWgyZbQnNMKbKqx4vIcbuOz+pR2Ax4hMKCDoyfAqjVW8rHf2IPsrZOd3hh3NHaX9WeVxm1d+YGqUpquVrLXeCyqu0MDl0QTeG9EebWXPVAIQ1e7NV6tpEb9GyymIif1MqVDDoJwzYc4adloGf8qWm1PDtje1AbsS9Cc6h6qIn5xX/G8EXany575Ckw+caKaDiI/eWah4TDkX7BHBRI3cBwZUO504uNPYLXxNOwJ5/D9/ajE4ittIIloWpWGC/cAo5azRSykaxyjCyv7LAJRLpbbIawePFwxA1zo0f6i2qM9fUYs+6/eWPbAAjMIBlshuMZ4AFpWtTO3NyaMxPd3dHE5n1YzWTfjAw47uGxYlGuQsPhA956xBPtMJZean5CiALB7q3CUuBQmrvvX6JkXhuZLOoj/0NNPpqrjDrkxcX/yxFEocX+bnxy9TBBkiTBwoxrHQHpx0DMtBQnHWjIFzh1/UbCdDioTexvFufpCVQ=
