language: python
git:
  depth: 3
branches:
  only:
  - master
python:
- '3.7'
install:
- pip install -r requirements.txt
script:
- python3 DeleteMyHistory.py
env:
  matrix:
  - UUU=kkk
  global:
    secure: D/kbqwGgM9MeGS11HVuvQGaw3OBaETpgXuAzSjcSj1BF7yqdPgMZDpUBDki1wnCeqmqcCXFkpPv9FCxY4Zw/Z/Fyhl/iaQxgM8jYOBNHrTCUN09UzEZD/eDoh1pV0njtVyqXgvNqk+ReGgOYtxhbUbPumUjHJkKYzHlMGhVxGM3jkpwEUUMui5n/8NIYyVeRa5j+Iqa5LdP0WKifisnQwQhIG0y0nK0SfVF5NdHZxVcJPac3cu1IoksL5Sm2erEU78P2L6/X9oMzIErNRgNJFhYUl/zTtCycwBMJLqIeHrfwCom+t35cSqtvwlDN0O9IwOc4qa+AYZMx9lO5xcb8XiaTzrxHc6Ps0vl4LYAsfOQ+l61QSO10TSZV5PmhJASh9J70UJTpMNf7r7f0dApypoY5nI+kKEjOacDBL2hMK3s8TSPqay93yBRhAYQ1qdHndBoyF8l6VA8OE4LdPmWNus55bsHEVzLbNi39SfZyRqEQBcl4SdJMaD/3HFcGyX4InjzHKVUlX74OBWGkqbpoTbwQV2yhDv+W74vhxap/mbXtc+zo+wggLsWHkHH7z+392iwh3OLBKLKUheeZjLmzrMP/hXTEP4TmyojClvHT/F39q4dLDT1RMDddGAqNg5ltscNCurczYgXmVMnmEAi4487ijXKi9/m/YljqejleFy8=
